# Generated by Django 5.2 on 2025-05-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_customuser_city_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='concept',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
